#!/usr/bin/env python3
"""Generate COMSTAR AO stock agent catalog from vendor agent_providers YAMLs."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROVIDERS = (
    ROOT
    / "vendor/agentic-orchestration/agentic-orchestration-tool/config/agent_providers"
)
OUT_JSON = ROOT / "terminal/bridge/lib/agents/ao_stock_agents.json"
OUT_DART = ROOT / "terminal/bridge/lib/agents/ao_stock_agents.g.dart"

SECRET_BY_TYPE = {
    "openai": [("OPENAI_API_KEY", "OpenAI API key", True)],
    "anthropic": [("ANTHROPIC_API_KEY", "Anthropic API key", True)],
    "ollama": [
        ("OLLAMA_HOST", "Ollama host", False),
        ("OLLAMA_API_BASE", "Ollama API base", False),
    ],
    "huggingface": [("HF_TOKEN", "Hugging Face token", True)],
    "vllm": [
        ("VLLM_API_KEY", "vLLM API key", True),
        ("VLLM_BASE_URL", "vLLM base URL", False),
    ],
    "jetstream": [("JETSTREAM_API_KEY", "JetStream API key", True)],
}


def parse_yaml_simple(text: str) -> dict:
    out: dict = {}
    for line in text.splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        if line.startswith(" ") or line.startswith("\t"):
            continue
        m = re.match(r"^([A-Za-z0-9_]+):\s*(.*)$", line)
        if not m:
            continue
        k, v = m.group(1), m.group(2).strip()
        if "#" in v:
            v = v.split("#", 1)[0].strip()
        if v in ("true", "false"):
            out[k] = v == "true"
            continue
        if re.fullmatch(r"-?\d+(\.\d+)?", v or ""):
            out[k] = float(v) if "." in v else int(v)
            continue
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
            v = v[1:-1]
        out[k] = v
    return out


def dart_str(s: str | None) -> str:
    if s is None:
        return "null"
    esc = (
        str(s)
        .replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\n", "\\n")
        .replace("\r", "")
    )
    return f"'{esc}'"


def main() -> None:
    agents = []
    for path in sorted(PROVIDERS.glob("*.yaml")):
        data = parse_yaml_simple(path.read_text(encoding="utf-8"))
        agent_id = str(data.get("id") or path.stem)
        typ = str(data.get("type") or "")
        secrets = [
            {"name": n, "label": label, "required": req, "secret": req}
            for n, label, req in SECRET_BY_TYPE.get(typ, [])
        ]
        agents.append(
            {
                "id": agent_id,
                "kind": "agent",
                "label": data.get("role") or agent_id,
                "role": data.get("role"),
                "description": data.get("planner_hint") or data.get("goal") or "",
                "provider": typ,
                "model": data.get("model"),
                "harnessProfile": data.get("harness_profile"),
                "requiredSecrets": secrets,
                "source": "ao_stock",
            }
        )

    payload = {
        "agents": agents,
        "generatedFrom": "vendor/.../agent_providers",
        "count": len(agents),
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    lines = [
        "// GENERATED by scripts/generate_ao_stock_agents.py — do not edit.",
        "// Full AO stock agent_providers pack for COMSTAR Admin enablement UI.",
        "library;",
        "",
        "/// AO stock agent catalog (may include providers not currently advertised",
        "/// by live `GET /api/v1/catalog`, e.g. gated / missing host secrets).",
        "const List<Map<String, Object?>> kAoStockAgents = [",
    ]
    for a in agents:
        secrets = a["requiredSecrets"]
        sec_lit = ", ".join(
            "{"
            f"'name': {dart_str(s['name'])}, "
            f"'label': {dart_str(s['label'])}, "
            f"'required': {'true' if s['required'] else 'false'}, "
            f"'secret': {'true' if s['secret'] else 'false'}"
            "}"
            for s in secrets
        )
        lines.append("  {")
        lines.append(f"    'id': {dart_str(a['id'])},")
        lines.append(f"    'kind': 'agent',")
        lines.append(f"    'label': {dart_str(a.get('label'))},")
        lines.append(f"    'role': {dart_str(a.get('role'))},")
        lines.append(f"    'description': {dart_str(a.get('description'))},")
        lines.append(f"    'provider': {dart_str(a.get('provider'))},")
        lines.append(f"    'model': {dart_str(a.get('model'))},")
        lines.append(f"    'harnessProfile': {dart_str(a.get('harnessProfile'))},")
        lines.append(f"    'requiredSecrets': <Map<String, Object?>>[{sec_lit}],")
        lines.append(f"    'source': 'ao_stock',")
        lines.append("  },")
    lines.append("];")
    lines.append("")
    OUT_DART.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_JSON} and {OUT_DART} ({len(agents)} agents)")


if __name__ == "__main__":
    main()
